POST http://localhost:3000/additem.test.php
Content-Type: application/x-www-form-urlencoded

itemID=3000
&itemName=Gibson les pual
&categoryID=100
&listPrice=1199.00
###
GET http://localhost:3000/listitems.test.php
###
POST http://localhost:3000/changeitem.test.php
Content-Type: application/x-www-form-urlencoded

itemID=3000
&itemName=Fender precision
&categoryID=100
&listPrice=299.00
###
POST http://localhost:3000/removeitem.test.php
Content-Type: application/x-www-form-urlencoded

itemID=3000

